import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ENDUSER
 */
public class home extends javax.swing.JFrame {
public int z = 0;    

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        btnProveedores.setVisible(false);
        btnPedidos.setVisible(false);
        btnProductos.setVisible(false);
        btnEmpleados.setVisible(false);
        btnClientes.setVisible(false);
        btnVentas.setVisible(false);
        btnIVA.setVisible(false);
        btnSalir.setVisible(false);
        btnCerrarApp.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnIVA = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCerrarApp = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/varita.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, -1, -1));

        btnProveedores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proveedores.png"))); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnProveedoresComponentShown(evt);
            }
        });
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, -1));

        btnPedidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pedidos.png"))); // NOI18N
        btnPedidos.setText("Orden de pedidos");
        btnPedidos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnPedidosComponentShown(evt);
            }
        });
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 220, -1));

        btnProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productos.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnProductosComponentShown(evt);
            }
        });
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 220, -1));

        btnEmpleados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empleados.png"))); // NOI18N
        btnEmpleados.setText("Empleados");
        btnEmpleados.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnEmpleadosComponentShown(evt);
            }
        });
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 220, -1));

        btnClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientes.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnClientesComponentShown(evt);
            }
        });
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 220, -1));

        btnVentas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/venta.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnVentasComponentShown(evt);
            }
        });
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 220, -1));

        btnIVA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIVA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IVA.png"))); // NOI18N
        btnIVA.setText("IVA");
        btnIVA.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnIVAComponentShown(evt);
            }
        });
        btnIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIVAActionPerformed(evt);
            }
        });
        getContentPane().add(btnIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 220, -1));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnSalirComponentShown(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 220, -1));

        btnCerrarApp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCerrarApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        btnCerrarApp.setText("Cerrar aplicacion");
        btnCerrarApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarAppActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 220, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homepage TRUE.jpeg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here: SALIR DE HOME
        int a = JOptionPane.showConfirmDialog(null,"Realmente deseas salir?","Selecciona",JOptionPane.YES_NO_OPTION);
        if(a == 0)
        {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCerrarAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarAppActionPerformed
        // TODO add your handling code here: SALIR DE LA APLICACION
        int a = JOptionPane.showConfirmDialog(null,"Realmente deseas salir?","Selecciona",JOptionPane.YES_NO_OPTION);
        if(a == 0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCerrarAppActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here: FLECHA AZUL
        if(z==0)
        {
            try{
                Thread.sleep(250);
                btnProveedores.setVisible(true);
                //jLabel1.setVisible(true);
            }
            catch(Exception e)
            {}
        }
        else
        {
        btnProveedores.setVisible(false);
        btnPedidos.setVisible(false);
        btnProductos.setVisible(false);
        btnEmpleados.setVisible(false);
        btnClientes.setVisible(false);
        btnVentas.setVisible(false);
        btnIVA.setVisible(false);
        btnSalir.setVisible(false);
        btnCerrarApp.setVisible(false);
        //jLabel1.setVisible(false);
        //jLabel2.setVisible(false);
        //jLabel3.setVisible(false);
        //jLabel4.setVisible(false);
        //jLabel5.setVisible(false);
        //jLabel6.setVisible(false);
        //jLabel7.setVisible(false);
        //jLabel8.setVisible(false);
        //jLabel9.setVisible(false);  
        z = 0;
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnProveedoresComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnProveedoresComponentShown
        // TODO add your handling code here: //MOSTRAR PROVEEDORES
        try{
                Thread.sleep(250);
                btnPedidos.setVisible(true);
                //jLabel2.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_btnProveedoresComponentShown

    private void btnPedidosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnPedidosComponentShown
        // TODO add your handling code here:MOSTRAR PEDIDOS
        try{
                Thread.sleep(250);
                btnProductos.setVisible(true);
                //jLabel3.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_btnPedidosComponentShown

    private void btnProductosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnProductosComponentShown
        // TODO add your handling code here: MOSTRAR PRODUCTOS
        try{
                Thread.sleep(250);
                btnEmpleados.setVisible(true);
                //jLabel4.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_btnProductosComponentShown

    private void btnEmpleadosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnEmpleadosComponentShown
        // TODO add your handling code here: MOSTRAR EMPLEADOS
        try{
                Thread.sleep(250);
                btnClientes.setVisible(true);
                //jLabel5.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_btnEmpleadosComponentShown

    private void btnClientesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnClientesComponentShown
        // TODO add your handling code here:MOSTRAR CLIENTES
        try{
                Thread.sleep(250);
                btnVentas.setVisible(true);
                //jLabel6.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_btnClientesComponentShown

    private void btnVentasComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnVentasComponentShown
        // TODO add your handling code here: MOSTRAR VENTAS
        try{
                Thread.sleep(250);
                btnIVA.setVisible(true);
                //jLabel7.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_btnVentasComponentShown

    private void btnIVAComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnIVAComponentShown
        // TODO add your handling code here: MOSTRAR IVA
        try{
                Thread.sleep(250);
                btnSalir.setVisible(true);
                //jLabel8.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_btnIVAComponentShown

    private void btnSalirComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnSalirComponentShown
        // TODO add your handling code here: MOSTRAR SALIDA
        try{
                Thread.sleep(250);
                btnCerrarApp.setVisible(true);
                //jLabel9.setVisible(true);
                z=1;
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_btnSalirComponentShown

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // TODO add your handling code here: DE HOMEPAGE HACIA PROVEEDORES
        new Proveedores().setVisible(true);
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here: DE HOMEPAGE A CLIENTES
        new Clientes().setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        // TODO add your handling code here:DE HOMEPAGE A EMPLEADOS
        new Empleados().setVisible(true);
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:DE HOMEPAGE A PRODUCTOS
        new Productos().setVisible(true);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        // TODO add your handling code here: DE HOMEPAGE A PEDIDOS
        new MenuPedido().setVisible(true);
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIVAActionPerformed
        // TODO add your handling code here:DE HOMEPAGE A IVA
        new IVA().setVisible(true);
    }//GEN-LAST:event_btnIVAActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        new Ventas().setVisible(true);
    }//GEN-LAST:event_btnVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarApp;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnIVA;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    // End of variables declaration//GEN-END:variables
}
