import java.sql.*;
import Project.ConnectionProvider;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.pdf.PdfPTable;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//LANTERAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
/**
 *
 * @author ENDUSER
 */
public class Pedido extends javax.swing.JFrame {
public double finalTotal=0;
public double IVA=0.16;
    /**
     * Creates new form Pedido
     */
    ConnectionProvider con;
    Connection conn;
    public Pedido() {
        initComponents();
        con=new ConnectionProvider();
        conn=con.getCon();
        
        SimpleDateFormat dFormat=new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        jLabel5.setText(dFormat.format(date));
        
        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now=LocalDateTime.now();
        jLabel6.setText(dtf.format(now));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 120));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registrar pedido icon.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Fecha:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Hora:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 60, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 87, 1164, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Detalles del empleado:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 103, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Nombre:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 210, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("No Clave:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 110, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, 1164, 10));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Telefono:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 248, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Detalles del proveedor:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 191, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Nombre:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 200, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("No Clave:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 110, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Nombre/empresa:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 232, -1, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 229, 191, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Correo:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(838, 232, -1, -1));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(913, 229, 241, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 263, 1164, 10));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Detalles del producto:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Nombre:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 190, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("No Clave:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 110, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Cantidad pedida:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 315, 185, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Descripcion:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, -1, -1));

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 315, 234, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButton1.setText("Agregar producto(s)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 350, -1, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 396, 1164, 10));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad", "Precio Unitario", "Importe", "NoClaveProducto"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 710, 159));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Total a pagar:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 110, 20));

        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 150, -1));

        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 140, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reset.png"))); // NOI18N
        jButton3.setText("Reiniciar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close Jframe.png"))); // NOI18N
        jButton4.setText("Cerrar ventana");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 540, 160, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Precio unitario:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registrar Orden.gif"))); // NOI18N
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("No Clave de Orden:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 0));
        jLabel26.setText("100");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("IVA:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("SubTotal:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 140, 30));

        jTextField16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 140, 30));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg pedidosss.jpeg"))); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:CHECK
        String nombreEmp=jTextField1.getText();
        try
        {
            conn = con.getCon();
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from empleado where nombre_empleado like '"+nombreEmp+"%'");
            if(rs.next())
            {
               jTextField1.setText(rs.getString(2)); 
               jTextField2.setText(rs.getString(1));  
               jTextField4.setText(rs.getString(4)); 
               jTextField1.setEditable(false);
            }
            else
            {
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField4.setText("");
                 JOptionPane.showMessageDialog(null,"Los datos no coinciden");
            }
                
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:CHECK
        String nombrePro=jTextField5.getText();
        try
        {
            conn = con.getCon();
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from proveedor where nombre_proveedor like '"+nombrePro+"%'");
            if(rs.next())
            {
               jTextField5.setText(rs.getString(2)); 
               jTextField6.setText(rs.getString(1)); 
               jTextField7.setText(rs.getString(3)); 
               jTextField8.setText(rs.getString(5)); 
               jTextField5.setEditable(false);
            }
            else
            {
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                jTextField8.setText("");
                 JOptionPane.showMessageDialog(null,"Los datos no coinciden");
            }
                
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:CHECK
        String IDEmp=jTextField2.getText();
        try
        {
            conn = con.getCon();
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from empleado where id_empleado like '"+IDEmp+"%'");
            if(rs.next())
            {
               jTextField1.setText(rs.getString(2)); 
               jTextField2.setText(rs.getString(1)); 
               //jTextField3.setText(rs.getString(2)); 
               jTextField4.setText(rs.getString(4)); 
               jTextField2.setEditable(false);
            }
            else
            {
                jTextField1.setText("");
                jTextField2.setText("");
                //jTextField3.setText("");
                jTextField4.setText("");
                 JOptionPane.showMessageDialog(null,"Los datos no coinciden");
            }
                
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:CHECK
        String IDPro=jTextField6.getText();
        try
        {
            conn = con.getCon();
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from proveedor where id_proveedor like '"+IDPro+"%'");
            if(rs.next())
            {
               jTextField5.setText(rs.getString(2)); 
               jTextField6.setText(rs.getString(1)); 
               jTextField7.setText(rs.getString(3)); 
               jTextField8.setText(rs.getString(5)); 
               jTextField6.setEditable(false);
            }
            else
            {
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                jTextField8.setText("");
                JOptionPane.showMessageDialog(null,"Los datos no coinciden");
            }
                
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:CHECK
        String nombreProducto=jTextField9.getText();
        try
        {
            conn = con.getCon();
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from producto where nombre_producto like '"+nombreProducto+"%'");
            if(rs.next())
            {
               jTextField9.setText(rs.getString(2)); 
               jTextField10.setText(rs.getString(1)); 
               jTextField11.setText("1"); 
               jTextField13.setText(rs.getString(5));
               jTextField12.setText(rs.getString(3));
               
            }
            else
            {
                jTextField9.setText("");
                jTextField10.setText("");
                jTextField9.setText("");
                jTextField11.setText("");
                jTextField12.setText("");
                jTextField13.setText("");
                JOptionPane.showMessageDialog(null,"Los datos no coinciden");
            }
                
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:CHECK
        String IDProducto=jTextField10.getText();
        try
        {
            conn = con.getCon();
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from producto where id_producto ='"+IDProducto+"'");
            if(rs.next())
            {
               jTextField9.setText(rs.getString(2)); 
               jTextField10.setText(rs.getString(1)); 
               jTextField11.setText("1"); 
               jTextField13.setText(rs.getString(5)); 
               jTextField12.setText(rs.getString(3)); 
            }
            else
            {
                jTextField9.setText("");
                jTextField10.setText("");
                jTextField9.setText("");
                jTextField11.setText("");
                jTextField12.setText("");
                jTextField13.setText(""); 
                JOptionPane.showMessageDialog(null,"Los datos no coinciden");
            }
                
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTextField10ActionPerformed
    public boolean buscaridproducto(int clave){
    int cantidad=0;
    double importe = 0;
    int x=0;
    Boolean ban=false;
    for( x=0;x<jTable1.getRowCount();x++){
        int clavetabla=Integer.parseInt(jTable1.getValueAt(x,4).toString());
        if(clavetabla==clave){
           cantidad=Integer.parseInt(jTable1.getValueAt(x,1).toString())+Integer.parseInt(jTextField11.getText());
           jTable1.setValueAt(cantidad,x,1);
           int canti=Integer.parseInt(jTable1.getValueAt(x,1).toString());
           double preci=Double.parseDouble(jTable1.getValueAt(x,2).toString());
           importe=canti*preci;
           ban=true;
           
        }
       
       jTable1.setValueAt(importe,x,3);
    }
    return ban;
}
    Object [][] data = new Object[10][5];
    public void getImporte(Boolean ban){
    double subtotal=0;
    double importe=0;
    int cantidad=0;
    double precio=0;
    if(ban==false){
         precio=Integer.parseInt(jTextField13.getText());
        cantidad=Integer.parseInt(jTextField11.getText());
        importe=cantidad*precio;
        
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();

    model.addRow(new Object[]{jTextField9.getText(),cantidad,jTextField13.getText(),importe,jTextField10.getText()});
     for( int x=0;x<jTable1.getRowCount();x++){
           int canti=Integer.parseInt(jTable1.getValueAt(x,1).toString());
           double preci=Double.parseDouble(jTable1.getValueAt(x,2).toString());
           importe=canti*preci;
          subtotal+=importe;
         jTable1.setValueAt(importe,x,3);
         data[x][0]=canti;
         data[x][1]=preci;
         data[x][2]=Integer.parseInt(jLabel26.getText());
         data[x][3]=Integer.parseInt((String)jTable1.getValueAt(x,4));
          }  
    }else{
        for( int x=0;x<jTable1.getRowCount();x++){
        
          
           int canti=Integer.parseInt(jTable1.getValueAt(x,1).toString());
           double preci=Double.parseDouble(jTable1.getValueAt(x,2).toString());
           importe=canti*preci;
          subtotal+=importe;
          jTable1.setValueAt(importe,x,3);
          data[x][0]=canti;
         data[x][1]=preci;
         data[x][2]=Integer.parseInt(jLabel26.getText());
         data[x][3]=Integer.parseInt((String)jTable1.getValueAt(x,4));
          }  
        
        }
        jTextField16.setText(String.valueOf(subtotal));
        jTextField15.setText(String.valueOf(subtotal*IVA));
        jTextField14.setText(String.valueOf(subtotal+(subtotal*IVA)));

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:BOTON AGREGAR   CHECK    
        int clave=Integer.parseInt(jTextField10.getText());
        getImporte(buscaridproducto( clave));
        
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:CERRAR DESDE PEDIDO
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:REINICIAR LIMPIAR CAMPOS
        setVisible(false);
        new Pedido().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
//CHECK
  public int getDetalleId() throws SQLException{
        int index=0;
            ResultSet rs;
            PreparedStatement st = conn.prepareStatement("select max(id_detalle_pedido) from detalle_pedido");
            st.executeQuery();
            rs= st.getResultSet();
            if(rs.next())
              index = rs.getInt(1)+1;
    return index;    
    };  
  
  public void actualizarstock(int productoid, int cantidadregistrada){
      //String pId=jTextField10.getText();
                try
                {
                    conn = con.getCon();
                    Statement st=conn.createStatement();
                    ResultSet rs=st.executeQuery("select * from producto where id_producto='"+productoid+"'");
                    if(rs.next())
                    {
                        String stockantes = (rs.getString(4));
                        //String cantidadregistrada = jTextField11.getText();
                        int cr=(cantidadregistrada);
                        int kk=Integer.parseInt(stockantes);
                        int nuevos=kk+cr;
                       try{
                    st.executeUpdate("update producto set stock='"+nuevos+"' where id_producto ='"+productoid+"'");

                    //JOptionPane.showMessageDialog(null,"Exitosamente actualizado");
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                } 
                    }
                    else
                        JOptionPane.showMessageDialog(null,"El ID del producto no existe");
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
  }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:GUARDAR CHECK
        if(jTextField1.getText().length()==0 || jTextField2.getText().length()==0 || jTextField6.getText().length()==0 || jTextField5.getText().length()==0 || jTextField15.getText().length()==0 || jTextField14.getText().length()==0 || jTextField16.getText().length()==0 || jTable1.getValueAt(0,0)==(null))
        {
            JOptionPane.showMessageDialog(null,"Por favor llene todos los campos");
        }
        else
        {
           String nombreEmp=jTextField1.getText();
        String idEmp=jTextField2.getText();
        //String cargo=jTextField3.getText();
        String telefonoEmp=jTextField4.getText();
        //////
        String nombrePro=jTextField5.getText();
        String idPro=jTextField6.getText();
        String nombreEmpresa=jTextField7.getText();
        String telefonoEmpresa=jTextField8.getText();
        String path="E:\\";
        com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
        try
        {
            PdfWriter.getInstance(doc, new FileOutputStream(path+"Llantera_PEDIDO"+jLabel26.getText()+"_"+nombreEmp+"_"+jLabel5.getText()+".pdf"));
            doc.open();
            Paragraph paragraph1=new Paragraph("Esparza Duran Kenia Jaqueline(CRONOS.Compañia Llantera Management System-PEDIDO)\n\nNumero de contacto:((+33)19432951)\n");
            doc.add(paragraph1);
            Paragraph paragraph2=new Paragraph("Fecha & Hora:"+jLabel5.getText()+" "+jLabel6.getText()+"\nDetalles del Empleado:\nID del Empleado:"+idEmp+"\nNombre:"+nombreEmp+"\nTelefono:"+telefonoEmp+"\n\n");
            doc.add(paragraph2);
            /////
            Paragraph paragraph3=new Paragraph("\nDetalles del Proveedor:\nID del Proveedor:"+idPro+"\nNombre:"+nombrePro+"\nNombre de la Empresa:"+nombreEmpresa+"\nTelefono:"+telefonoEmpresa+"\n\n");
            doc.add(paragraph3);
            Paragraph paragraph4=new Paragraph("\nDetalles del Pedido:\n\n");
            doc.add(paragraph4);
            PdfPTable tb1=new PdfPTable(5);
            tb1.addCell("Nombre");
            tb1.addCell("Cantidad");
            tb1.addCell("Precio Unitario");
            tb1.addCell("Importe");
            tb1.addCell("No Clave del producto");
            for(int i=0;i<jTable1.getRowCount();i++)
            {
                String n=jTable1.getValueAt(i,0).toString();
                String d=jTable1.getValueAt(i,1).toString();
                String r=jTable1.getValueAt(i,2).toString();
                String q=jTable1.getValueAt(i,3).toString();
                String s=jTable1.getValueAt(i,4).toString();
                tb1.addCell(n);
                tb1.addCell(d);
                tb1.addCell(r);
                tb1.addCell(q);
                tb1.addCell(s);
            }
            doc.add(tb1);
            //Paragraph paragraph5=new Paragraph("\nTotal: "+jTextField14.getText()+"\nMonto de pago: "+jTextField15.getText()+"\nCambio: "+jTextField16.getText()+"\n\nGracias por usar el programa! Por favor, vuelva pronto.\nPaper Company System Judy.CO");
            Paragraph paragraph5=new Paragraph("\nIVA: $"+jTextField15.getText()+"\nSubTotal: $"+jTextField16.getText()+"\nTotal: $"+jTextField14.getText()+"\n\n\nGracias por usar el programa! Por favor, vuelva pronto.\nCRONOS.Compañia llantera Management System");
            doc.add(paragraph5);
            JOptionPane.showMessageDialog(null,"Pedido generado");
            setVisible(true);
            new Pedido().setVisible(true);
            /////////////////////////////
            try{
                String idPedido = jLabel26.getText();
                String fechapedido =  jLabel5.getText();
                String idEmpleadopedido = jTextField2.getText();
                String idProveedorpedido = jTextField6.getText();
                PreparedStatement stmt=conn.prepareStatement("insert into pedido values(?,?,?,?)");
                stmt.setInt(1, Integer.parseInt(idPedido));
                stmt.setString(2, fechapedido);
                stmt.setString(3, idEmpleadopedido);
                stmt.setString(4, idProveedorpedido);
                stmt.executeUpdate();
                try{
                    for(int x=0;x<10;x++){
                    PreparedStatement stmtDetalle=conn.prepareStatement("insert into detalle_pedido values(?,?,?,?,?)");
                stmtDetalle.setInt(1, getDetalleId());
                stmtDetalle.setInt(2, Integer.parseInt(data[x][0].toString()));//cantidad
                stmtDetalle.setDouble(3,Double.parseDouble(data[x][1].toString()));//precio
                stmtDetalle.setInt(4, Integer.parseInt(data[x][2].toString()));//pedidoid foreign key
                stmtDetalle.setInt(5, Integer.parseInt(data[x][3].toString()));//producto foreign key
                
                stmtDetalle.executeUpdate();
                 actualizarstock(Integer.parseInt(data[x][3].toString()),Integer.parseInt(data[x][0].toString()));
                }
    
                }catch(Exception e)
                {
                   //JOptionPane.showMessageDialog(null,e);
                }
                //JOptionPane.showMessageDialog(null,"Exitosamnete Registrado");
                setVisible(false);
                new Pedido().setVisible(true);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"No se registro correctamente");
            }
            
        }
        catch(Exception e)
        {
          JOptionPane.showMessageDialog(null,e);  
        }
        doc.close(); 
        }
        /////////////////////////////////////
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
       //////////////
        jTextField4.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField12.setEditable(false);
        jTextField14.setEditable(false);
        jTextField15.setEditable(false);
        jTextField16.setEditable(false);
       ///////////
        try
        {
           ResultSet rs;
           PreparedStatement st = conn.prepareStatement("select max(id_pedido) from pedido");
           st.executeQuery();
           rs= st.getResultSet();
           if(rs.first())
           {
               int id=rs.getInt(1);
               id=id+1;
               String str=String.valueOf(id);
               jLabel26.setText(str);
           }
           else
               jLabel26.setText("1");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
